### ISSUE TITLE
Imput Method ui position is incorrect

### ISSUE THREAD

**Issue by 734vin** [pthom/imgui_bundle#111]
<img width="744" alt="WeChatdb47fa9b948658f1f1de85da030e53ec" src="https://github.com/pthom/imgui_bundle/assets/56961542/a277055f-48a1-4e63-b99b-ceb7a52d6902">

Imput Method UI always at left-bottom of screen

**Comment by pthom** [comment]
Hum, this is an issue which I cannot reproduce on my local English system. 
However I suspect this issue is related to ImGui in itself, not ImGui Bundle. May be you should look in the Imgui repo for issues and questions about this

**Comment by 734vin** [comment]
as i kown, it's a feature about system.
in project imgui, it's implemented in various backend.

any way,  thanks for your works

**Comment by pthom** [comment]
Just a quick remark, I just added imgui.get_io().set_platform_ime_data_fn in the python bindings.

See 29949f8023248d6160bcfca3daeeb248eef6caef

May be this will help if your issue was when using python.
