### ISSUE TITLE
Pyglet support

### ISSUE THREAD

**Issue by jc211** [pthom/imgui_bundle#114]
Hi,
Do you have any advice as to how I can implement pyglet support for imgui_bundle?

**Comment by pthom** [comment]
Hi,

ImGui Bundle does not support pyglet by default.

 As an alternative, [pyimgui](https://github.com/pyimgui/pyimgui) is another library that offers pythonbindings for ImGui. It has support for pyglet, however it does not support the docking features of ImGui, and does not provide the additional library that ImGui Bundle provides.

If you want to explore how support for pyglet could be added, here are some quick advices:

1. You should take inspiration from the example [imgui_example_glfw_opengl3.py](https://github.com/pthom/imgui_bundle/blob/main/bindings/imgui_bundle/demos_python/demos_immapp/imgui_example_glfw_opengl3.py)

Basically, you will have to adapt there all the call to glfw (and replace them by pyglet), and you may also have to also reimplement the OpenGL rendering.

2. Inspiration on pyglet usage with ImGui:
You can look at the [pyglet.py](https://github.com/pyimgui/pyimgui/blob/master/imgui/integrations/pyglet.py) file from pyimgui for inspiration

3. Inspiration on how to implement the OpenGL rendering
In the example, the OpenGL rendering is done via these lines:

```python
        GL.glClear(GL.GL_COLOR_BUFFER_BIT)
        imgui.backends.opengl3_render_draw_data(imgui.get_draw_data())
```

I suspect this may also work with pyglet. However, if you need to implement the rendering yourself, you can take inspiration from [opengl.py](https://github.com/pyimgui/pyimgui/blob/master/imgui/integrations/opengl.py), also from the  pyimgui project.


Please keep me informed if you end up exploring this.

**Comment by pthom** [comment]
Hi,

There is now a working python backend for pyglet: 
see https://github.com/pthom/imgui_bundle/blob/main/bindings/imgui_bundle/python_backends/pyglet_backend.py
and an example:
https://github.com/pthom/imgui_bundle/blob/main/bindings/imgui_bundle/python_backends/examples/example_python_backend_pyglet.py

**Comment by jc211** [comment]
This is great but I think you forget to implement on_mouse_drag:
https://github.com/pthom/imgui_bundle/blob/ba617dbe9bb92f18f9aadd7ff694d843cc34eac6/bindings/imgui_bundle/python_backends/pyglet_backend.py#L163

I just copied it from here:
https://github.com/pyimgui/pyimgui/blob/723022d87de8040d1c4a66f53288dcfd7d2274d3/imgui/integrations/pyglet.py#L144
