### ISSUE TITLE
Hovering a Pin when adding a Link is causing the canvas to clip

### ISSUE THREAD

**Issue by krejov100** [pthom/imgui_bundle#117]
I have found that the node editor canvas is clipping when attempting to create a link.
I believe it is related to this issue in the underlying imgui-node-editor, which has a workaround. 
https://github.com/thedmd/imgui-node-editor/issues/237

https://github.com/pthom/imgui_bundle/assets/5153498/d25ac2cd-ccbc-4b2d-9cf1-be454dcce694

**Comment by pthom** [comment]
Hi,

It is strange that [the issue](https://github.com/thedmd/imgui-node-editor/issues/237) was closed in the imgui-node-editor repository. Having an issue or a related PR would be the best way to get this to be solved in the main repository. 

Did you try the workaround on your side with your project, and does it fix the issue?

**Comment by krejov100** [comment]
I have not reproduced the workaround, I've been using the precompiled wheel from pip. 
I did also find this possibly related issue that remains open on the imgui-node-editor repository.

https://github.com/thedmd/imgui-node-editor/issues/205

**Comment by pthom** [comment]
Could you post a minimal reproducible example?

**Comment by krejov100** [comment]
To reproduce, it requires the graph to be in a docking window, and the clipping is screen position depended. 

```python
from imgui_bundle import imgui, imgui_node_editor as ed, immapp
from imgui_bundle.immapp import static, run_anon_block as anon
from imgui_bundle import hello_imgui


@immapp.static(id=0)
def next_id():
    next_id.id += 1
    return next_id.id

@immapp.static(id=0)
def next_link_id():
    next_link_id.id += 1
    return next_link_id.id

def gui():
    next_id.id = 0

    ed.begin("My Editor", imgui.ImVec2(0.0, 0.0))

    ed.begin_node(ed.NodeId(next_id()))
    imgui.text("Node 1")
    ed.begin_pin(ed.PinId(next_id()), ed.PinKind.output)
    imgui.text("Out ->")
    ed.end_pin()
    ed.end_node()

    ed.begin_node(ed.NodeId(next_id()))
    imgui.text("Node 2")
    ed.begin_pin(ed.PinId(next_id()), ed.PinKind.input)
    imgui.text("-> In")
    ed.end_pin()
    ed.end_node()

    if ed.begin_create():
        input_pin_id = ed.PinId()
        output_pin_id = ed.PinId()
        if ed.query_new_link(input_pin_id, output_pin_id):
            if ed.accept_new_item():
                ed.link(ed.LinkId(next_link_id()), input_pin_id, output_pin_id)
    ed.end_create()

    ed.end()


runner_params = immapp.RunnerParams()
runner_params.imgui_window_params.menu_app_title = "Pipeline"
runner_params.imgui_window_params.enable_viewports = True
win = hello_imgui.DockableWindow()
win.gui_function = gui
win.label = "graph"
runner_params.docking_params.dockable_windows = [win]

add_on_params = immapp.AddOnsParams()
add_on_params.with_node_editor = True

immapp.run(runner_params, add_on_params)
```
<img width="799" alt="Screenshot 2023-07-04 at 10 47 57 AM" src="https://github.com/pthom/imgui_bundle/assets/5153498/6aaf2455-06f2-4307-a9d5-ec5664960546">

**Comment by pthom** [comment]
Yes, the workaround seems to solve the issue. 
I will consider adding this to my node fork, will keep you posted

**Comment by bighojae** [comment]
Thank you for reproducing!

**Comment by krejov100** [comment]
Thank you for reproducing!

**Comment by pthom** [comment]
Hi, I just pushed a commit that correct this:

* [https://github.com/pthom/imgui-node-editor/commit/471bdda7adaa230928f87b6a20de192d5af69580](correction in the node editor fork)
* [https://github.com/pthom/imgui_bundle/commit/79bde7de7bc1cb8c808123d9850c39428332d1f0](update submodule in this repository)

As of now, I did not release a new version of the pip package (this might take a few weeks, as I want to group updates).
 If you want the modification on your side, you will need to build the pip package from source.

```
git clone https://github.com/pthom/imgui_bundle.git
cd imgui_bundle
git submodule update --init --recursive  # Since there are lots of submodules, this might take a few minutes
pip install -v . # The build process might take up to 15 minutes
pip install opencv-contrib-python
```

**Comment by pthom** [comment]
I'll need to find an appropriate way to transmit the fix to @thedmd, together with an easily reproducible example.

I'll work on this a little later.

**Comment by thedmd** [comment]
@pthom Issue is now resolved in node editor. Thanks for your help!

**Comment by pthom** [comment]
This issue is now fixed, and also fixed in @thedmd  repo. Thanks a lot!
