### ISSUE TITLE
missing #include <cstdint> in fplus.hpp

### ISSUE THREAD

**Issue by digitalsignalperson** [pthom/imgui_bundle#138]
When trying to install from source for both python and C++ I had compile errors in fplus.hpp with many errors like `‘int64_t’ in namespace ‘std’ does not name a type`. 

The section that seemed to need the include is here around line 7448
https://github.com/pthom/imgui_bundle/blob/b39daddef097e2054074ce106c7f62461c4495e9/external/fplus/fplus/fplus.hpp#L7448

adding `#include <cstdint>` here and the builds work now

**Comment by pthom** [comment]
Hi, 

Thanks for letting me know! I just updated fplus, it should be ok now.
