### ISSUE TITLE
BUG: interactive manual - flipped images

### ISSUE THREAD

**Issue by dimateos** [pthom/imgui_bundle#140]
Hello Pascal!

I think there is an issue with the live version of the interactive manual.

The images are flipped in the Y axis.
At least in my end, with 3 different browsers, etc.
Collegue has the same issue, but our machines are pretty similar and under the same VPN etc.

![image](https://github.com/pthom/imgui_bundle/assets/26868611/78198591-b231-4f0b-ae23-087c2a26c547)

cheers

**Comment by pthom** [comment]
This is very strange! I need to investigate this. Thanks for reporting this!

**Comment by pthom** [comment]
... And now it is broken... I'm working on it!

**Comment by pthom** [comment]
This is now fixed. I don't even know what happened. By the way, the interactive manual was as well as the doc were largely updated.
Note: ImGui test Engine support is not yet official
