### ISSUE TITLE
Make it possible to implement the backend in python (original title: Include Python bindings for `ImDrawData` and `ImDrawList` arrays)

### ISSUE THREAD

**Issue by tpwrules** [pthom/imgui_bundle#142]
This would be useful for direct Python control of the drawing process, done e.g. [here](https://github.com/moderngl/moderngl-window/blob/f527bc440d4473701f59b6f08ed48df5754ecad4/moderngl_window/integrations/imgui.py#L207) and other program designs which allow full Python control of the rendering process.

For some reason the binding generation for the draw list array is explicitly disabled [here](https://github.com/pthom/imgui_bundle/blame/3adbfb2c2dac86c873491004c9eeb6b174b97ff0/external/imgui/bindings/litgen_options_imgui.py#L182) and for some other reason the vertex and index lists don't appear.

Is there any reason this couldn't be changed?

**Comment by pthom** [comment]
Hi,

The reason this is disabled is because ImVector is

**Comment by pthom** [comment]
Hi

ImVector is a template class, and this requires more work for python bindings. Fortunately, my generator supports templates; but after a first run, I saw that it requires some adaptations. 
I will study the feasibility.

**Comment by pthom** [comment]
Hi @tpwrules ,

I added bindings for almost ImVector instances. See https://github.com/pthom/imgui_bundle/commit/2b91325fc651a4c46832b738556a6020420e2ddc and c68585f50b2d52d4ed59b08e3f37481ae63588fb

As a result, it becomes possible to implement the backend in python. See [example here](https://github.com/pthom/imgui_bundle/tree/main/bindings/imgui_bundle/python_backends_wip) (work in progress!), where I implemented a manual rendering in python, using glfw + opengl backend; 

This  is inspired from [pyimgui's bindings](https://github.com/pyimgui/pyimgui) bindings. 
There is still some work to do on this side. I will not have time to study this in the near future. 
Contributions on this aspect are welcome, if you are willing to.

**Comment by tpwrules** [comment]
Thanks for the head start. I am not sure if I can contribute back what I will do but hopefully this makes an integration with ModernGL possible. Maybe it will be contributed back to that project, I'm not sure yet.

**Comment by tpwrules** [comment]
I did get this working, thanks for the fixes.
