### ISSUE TITLE
MSVC debug assertion failed due to the imgui_demo.cpp `isspace` call.

### ISSUE THREAD

**Issue by vertexi** [pthom/imgui_bundle#145]
When dynamically initializing the `DemoCodeWindow GDemoCodeWindow;` variable, the `isspace` function inside the `CodeLineStartsWith()` be called. Because of the initial value at `haystack` is negative, the `c >= -1 && c <= 255` Debug assertion failed inside `isspace()`.

https://github.com/pthom/imgui/blame/812f25683087ec5ca6c0802da6e40f682459ae25/imgui_demo.cpp#L8945

Maybe initialize the `char line_buffer[2048];` to zeros?

**Comment by pthom** [comment]
I will prepare a fix quickly, please tell me if it solves the issue.

**Comment by pthom** [comment]
(the fix is not that easy, because the code is in a fork of ImGui that I maintain)

**Comment by pthom** [comment]
It should be ok now, please let me know if it is ok on your side

**Comment by vertexi** [comment]
Looks good. Nice job! Thank you.
