### ISSUE TITLE
input data type for draw list `add_polyline`

### ISSUE THREAD

**Issue by kuchi** [pthom/imgui_bundle#148]
imgui_bundle version 1.0.0

I am trying to utilize 

    dl = implot.get_plot_draw_list()
    dl.add_polyline(data, len(data), col=draw_color, flags=0, thickness=1)

I am not sure how to correctly construct the input data. It looks like in the C imgui code it wants a pointer to a list of `ImVec2` items. But if I construct a python list of` ImVec2` items that does not work. It gives the following error:

       TypeError: add_polyline(): incompatible function arguments. The following argument types are supported:
        1. (self: imgui_bundle._imgui_bundle.imgui.ImDrawList, points: imgui_bundle._imgui_bundle.imgui.ImVec2, num_points: int, col: int, flags: int, thickness: float) -> None

The python wrapping appears to only support a single `ImVec2` element but I think it needs to take a list of ImVec2 items. Is there a way to properly construct this list to pass data to the function in python?

Thanks.

**Comment by pthom** [comment]
Hello,

This binding was incorrect, I just corrected it: see 03501e4fecf5e5b99d7b8759e64a56341d877792

You will have to build imgui_bundle from source: see [ìnstall instructions](https://pthom.github.io/imgui_bundle/install-instructions.html)
