### ISSUE TITLE
interal.Window name field is missing

### ISSUE THREAD

**Issue by dcnieho** [pthom/imgui_bundle#159]
Hi! Still using your libraries with much pleasure! Right now i am trying to port https://github.com/ocornut/imgui/issues/5484#issuecomment-1189989347 to python code. I am running into the problem that the name field of a window is not provided by imgui_bundle's imgui. There is `name_buf_len`, but not `name`. 
I'd like to be able to do `imgui.get_current_context().current_window.name`. Could you look into wrapping this?

Thanks as always!

**Comment by pthom** [comment]
Hello Diederick,

I do not have time to work on this right now, but you could try this:

add 
include <string> at the top
+
    pyClassImGuiWindow.def_readonly("name", &[](const ImGuiWindow& w) { return std::string(ImGuiWindow::Name) });

below the autogenerated code inside external/imgui/bindings/pybind_imgui_internal.cpp

Can you tell me if it is sufficient?

**Comment by dcnieho** [comment]
Hi Pascal,

No worries. I no longer have a setup where i can easily compile my own imgui_bundle, so can't test that for you. I have a workaround for my use case as the code doesn't need to be general (I know the parent name). So lets leave this open so its not forgotten to be done at some point?

Thanks!
Dee

**Comment by dcnieho** [comment]
Cool, thanks!
I don't know if i've set it yet, but, merry christmas andhappy holidays!

**Comment by dcnieho** [comment]
This works, thanks!
