### ISSUE TITLE
How to add colored glyphs or emojis?

### ISSUE THREAD

**Issue by ShaiAvr** [pthom/imgui_bundle#161]
I want to create text with emojis and colored glyphs with ImGui. I tried to follow the instructions of [imgui](https://github.com/ocornut/imgui/blob/master/docs/FONTS.md#using-colorful-glyphsemojis), but couldn't get it to work. Specifically, I couldn't find the `ImGuiFreeTypeBuilderFlags_LoadColor` flag.
Can you show how to include emojis in text? I also think it's a good idea to add an example on how to that in the demos. It's a nice feature for modern applications and I want to use it in my project.

**Comment by pthom** [comment]
Hi,

At the moment, imgui is not compiled with Freetype support inside imgui bundle, and thus it cannot support colored emojis.

A possible improvement in the future, but it would require two additional dependencies (Freetype + lunasvg), and that makes it a bit hard.

**Comment by ShaiAvr** [comment]
@pthom Cool. Can't wait for the next release on PyPi. I think I'll close this issue for now.
