### ISSUE TITLE
Can't set imgui.get_io().ini_filename

### ISSUE THREAD

**Issue by pthom** [pthom/imgui_bundle#17]
> Q: This should work, but doesn’t: ... imgui.get_io().ini_filename = ...

Well, an automatic generation for `const char * ImGuiIO::IniFilename" is hopeless, since it provides absolutely no storage.
I had to do a manual patch: https://github.com/pthom/imgui_bundle/commit/6ef5df6447eb146fc89fc392618f89c0b0be4940

A: use `imgui.set_io_ini_filename()` instead

**Comment by pthom** [comment]
I will leave this issue opened for reference for a while, but it is solved

**Comment by dcnieho** [comment]
I just updated an app from version 0.9.0 to 1.3.0, and ran into `imgui.get_io().ini_filename` no longer existing (it did in 0.9.0). Is this intended? This is an app that doesn't use hello_imgui functionality, but directly uses imgui_bundle.imgui and the backends.

**Comment by pthom** [comment]
`set_ini_filename` still exists, but `ini_filename` does not anymore. This is the result of [painstaking battle](set_ini_filename) where I discovered that using std::string in the ImGui code can lead to subtle bugs on certains platforms / compilers.

**Comment by pthom** [comment]
You should soon have access also to get_ini_filename, and a wheel here: 

https://github.com/pthom/imgui_bundle/actions/runs/7804616436

with this [commit](https://github.com/pthom/imgui_bundle/commit/b66c6dd29d774450e7b77de6c10861b6c30d5348)

**Comment by dcnieho** [comment]
Thanks! Tested, works.
By the way, i see warnings about using `upload-artifact@v3`
See this commit for what i had to do to make it work with v4: https://github.com/dcnieho/Titta/commit/1fe6f8ac7e279f2600a188e678781f385b3039ef. Quite nice actually, as now its now one huge zip file

**Comment by dcnieho** [comment]
When do you plan to make a new release?

**Comment by dcnieho** [comment]
I spoke too soon, this doesn't work.
I call `imgui.io.set_ini_filename('<some fully qualified path>/imgui.ini')` and when i after that call `imgui.io.get_ini_filename()`, i get `imgui_log.txt` as return value. I see that here, https://github.com/pthom/imgui/compare/f5aaf1bbe2944324eb729b2f3c7561ffd1523494...436590678d357f3e71745cf8aae309b6088dbc39#diff-cee9beb740469eb5192dfe94aaee7320932590adade9d9b1d2ee392ac2e1e88c, you mixed up the bodies of the two functions.

**Comment by pthom** [comment]
This is now fixed, with upload-artifact@v4 (thanks for the info).

I do not plan to make a release soon, since I'm dangerously close to the 10GB limit on Pypi.
