### ISSUE TITLE
gcc 8 support? (Ubuntu 20.04 LTS)

### ISSUE THREAD

**Issue by thejasonfisher** [pthom/imgui_bundle#179]
I think I'm stuck with gcc 8 (and ideally python 3.8.10) on an edge-device OS limitation of Ubuntu 20.04 -- causes magic_enum issues that I think are breaking the compile and pip install.

Is there an older version that might be compatible?

**Comment by pthom** [comment]
Could you try to install clang, it should be possible to install a more recent clang on ubuntu. Concerning python, I recommend python 3.9+, but you can try with python 3.8

**Comment by thejasonfisher** [comment]
Sorry, I was able to switch to gcc-9 and compile/install successfully.  Just migrated my application over and it is going great.

Thank you!
