### ISSUE TITLE
Try to build using Nuitka

### ISSUE THREAD

**Issue by hugle** [pthom/imgui_bundle#199]
I was trying to build the example code [`imgui_example_glfw_opengl3.py`](https://github.com/pthom/imgui_bundle/blob/main/bindings/imgui_bundle/demos_python/demos_immapp/imgui_example_glfw_opengl3.py) into standalone app using Nuitka, but faced an issue when running the executable, I have raised the issue in Nuitka side:

[Nuitka issue?](https://github.com/Nuitka/Nuitka/issues/2812)

Has anybody encountered this before?

**Comment by pthom** [comment]
Hello,
I don't have any experience with Nuitka, sorry.

**Comment by hugle** [comment]
Thanks for the awesome project @pthom , I can package examples using `hello_imgui` without issue using Nuitka. The glfw example runs fine, but maybe some hidden packaging process is required from Nuitka when dealing with glfw.
