### ISSUE TITLE
Expose some additional `implot` internal functions to allow custom plots

### ISSUE THREAD

**Issue by kuchi** [pthom/imgui_bundle#202]
If it's not a huge effort, would it be possible to include additional functions from `implot_internal.h` to allow creation of more custom plots. I am trying to have some custom displays for very large data sets that the below functions would be of use.

The following functions would be quite useful:

``` C++

// Begins a new item. Returns false if the item should not be plotted. Pushes PlotClipRect.
IMPLOT_API bool BeginItem(const char* label_id, ImPlotItemFlags flags=0, ImPlotCol recolor_from=IMPLOT_AUTO);


// Returns true if the user has requested data to be fit.
static inline bool FitThisFrame() 


// Extends the current plot's axes so that it encompasses a vertical line at x
static inline void FitPointX(double x) 


static inline void FitPointY(double y) 

static inline void FitPoint(const ImPlotPoint& p) 


```

**Comment by pthom** [comment]
Hello Anthony,

Those functions are available inside implot.internal:

FitThisFrame: https://github.com/pthom/imgui_bundle/blob/5da99660c98aca259f4b6d356ee70e763152d33c/bindings/imgui_bundle/implot/internal.pyi#L1924

BeginItem: https://github.com/pthom/imgui_bundle/blob/5da99660c98aca259f4b6d356ee70e763152d33c/bindings/imgui_bundle/implot/internal.pyi#L1842

FitPoint(X/Y): https://github.com/pthom/imgui_bundle/blob/5da99660c98aca259f4b6d356ee70e763152d33c/bindings/imgui_bundle/implot/internal.pyi#L1935-L1959

**Comment by kuchi** [comment]
Thank you Pascal. It didn’t even occur to me to import the sub module. I figured I was just overlooking something. Sorry to have bugged you and thanks so much for the help.
