### ISSUE TITLE
ImSpinner Version Bump - Resolves Multiple Def Compilation Errors

### ISSUE THREAD

**Issue by mrawlingst** [pthom/imgui_bundle#209]
I noticed that ImSpinner was last "updated" (added as repo) back in 2022. If you tried to include ImSpinner in a header file that is used by multiple *.cpp (as is common), it will throw compilation errors that there are multiple definitions. There was an issue already opened on ImSpinner's repo: https://github.com/dalerank/imspinner/issues/10

This issue has been resolved in these two commits that happened in 2023:
- https://github.com/dalerank/imspinner/commit/29f7a740276d8b39640126dcc71bf79e77a65370
- https://github.com/dalerank/imspinner/commit/c5e4fbb6b4b8ecd8a90927bc34ea8c3bf3434aaf

Just asking for version bump of the ImSpinner in this bundle.

**Comment by pthom** [comment]
Hello

Done, see https://github.com/pthom/imgui_bundle/commit/0398bb43b3e98ec1f4b1fa2701b0bfb619a17bbf

**Comment by mrawlingst** [comment]
I can verify that the latest changes has fixed this issue. Thanks!

**Comment by mrawlingst** [comment]
I can verify that the latest changes has fixed this issue. Thanks!
