### ISSUE TITLE
imgui_tex_inspect displays incorrect color value of texture in windows

### ISSUE THREAD

**Issue by ankerSlicerTeam** [pthom/imgui_bundle#211]
![a1dc6c29-bc14-43fd-9c65-6824dfc534de](https://github.com/pthom/imgui_bundle/assets/135973681/e51f9869-4e6c-4c0c-9722-e5ceb006d141)

**Comment by pthom** [comment]
This is likely an issue in [ImGuiTexInspect](https://github.com/andyborrell/imgui_tex_inspect)

This demo only calls ImGuiTexInspect::ShowDemoWindow():
```cpp
int main(int, char **)
{
    HelloImGui::SetAssetsFolder(DemosAssetsFolder());
    HelloImGui::SimpleRunnerParams runnerParams{.guiFunction = ImGuiTexInspect::ShowDemoWindow, .windowSize={1000, 1000}};
    ImmApp::AddOnsParams addOnsParams;
    addOnsParams.withTexInspect = true;
    ImmApp::Run(runnerParams, addOnsParams);
    return 0;
}
```

If you need to get pixel values, I advise you to use ImmVision which you can see in the [demo](https://traineq.org/ImGuiBundle/emscripten/bin/demo_imgui_bundle.html)

**Comment by ankerSlicerTeam** [comment]
Thank you for your answer. I have found the reason. imgui_tex_inspect sets a fixed value (512,512) when setting the texture size. However, when the image size is not (512,512), the texture is resized, and then the output rgba result is not displayed as shown after resize.   By the way, ImmVision is a great tool and admire your excellent contribution

**Comment by ankerSlicerTeam** [comment]
> Thank you for your answer. I have found the reason. imgui_tex_inspect sets a fixed value (512,512) when setting the texture size. However, when the image size is not (512,512), the texture is resized, and then the output rgba result is not displayed as shown after resize. By the way, ImmVision is a great tool and admire your excellent contribution

in imgui_tex_inspect_demo.h line 19:
```
Texture LoadTexture(const char * path)
{
    auto textureId = HelloImGui::ImTextureIdFromAsset(path);
    Texture r;
    r.size = ImVec2(512.f, 512.f); // This function is only by used the demo, which uses a 512x512 image
    r.texture = textureId;
    return r;
}
```

**Comment by ankerSlicerTeam** [comment]
However, the size of demo_tex_inspect.png displayed is 218*218

**Comment by pthom** [comment]
Ok thanks a lot for letting me know. I updated the code that sets the texture size. See these commits [in the ImGuiTexInspect fork](https://github.com/pthom/imgui_tex_inspect/commit/47cd57d33dd118c8be2771da0fe6ebdadd7cb937) and [in Dear ImGui Bundle](https://github.com/pthom/imgui_bundle/commit/658bc8b482f33c56c1d4c208a0d23eeb31111597).
