### ISSUE TITLE
implot.get_style().colors is not available

### ISSUE THREAD

**Issue by dcnieho** [pthom/imgui_bundle#221]
the colors array in `implot.Style` is not wrapped, so for instance `implot.get_style().colors` is not available.
I suppose this is the same issue as for `imgui.get_style().colors`, which you wrapped with two functions, `color_()` and `sel_color_()`. Could you make this available for the implot colors as well?

**Comment by pthom** [comment]
Done in https://github.com/pthom/imgui_bundle/commit/0fddd50209f2ba6053789d8d12856717fafa2025

PS: I just answered your email

**Comment by dcnieho** [comment]
Thanks! I left a comment on the commit (seems a doc was lost) and will test the wheels later tonight
