### ISSUE TITLE
Multiple threaded instances/windows of immapp/hello_imgui

### ISSUE THREAD

**Issue by Johndeep** [pthom/imgui_bundle#223]
A simple question, since I tried to look for Python Code documentation of hello_imgui or immapp and found nothing yet.

Is it possible to tell hello_imgui or immapp (which is a thin extension to hello_imgui anyway, well according to the description) to create non blocking windows, so I can run two or more separated windows simultaneously?

It seems that even with `threading` library it is not possible. In that case, hello_imgui will just silently do nothing and exit the code.

My plan is to run one or more hello_imgui windows alongside with a general glfw window or, for example, pyvista or something.

**Comment by Johndeep** [comment]
Okay, I found a solution for this. It is rather simple actually, well, with some limitations.
Instead of the `threading` or `concurrent.future` library, just use `multiprocessing` library.

Unlike threads, which shares context and data, processes do not do that. Thus it is possible to call upon multiple immapp/hello_imgui windows as easy as running the code multiple times with different parameters.

The limitation is obviously that the data is not shared but duplicated and then handled completely isolated from each other.

I still leave this thread open since I would like to know, if immapp/hello_imgui does have a not documented way to be started non blocking. Or if this feature is planned in a way.

**Comment by pthom** [comment]
Yes, apart from using the multi-processing library, I don't see any easy solution. GUI application often require to be run on the main thread, which we can emulate with multiprocessing. 

Even if you were to succeed in using a thread, you would encounter probably issues with some static variables which are present in Dear ImGui and Dear ImGui Bundle (Most of them are `static` not `thread_local`). The global ImGui Context Here is a probable example.

**Comment by Johndeep** [comment]
I tried to do threads again and found out that is **does** work, as long as I keep it at only one instance. As soon as I add another window per thread, everything just shuts down. Just like that.

For those who walk this path and want to have some more window to window interaction:

1. If you want to signal every other windows to close which run besides hello_imgui with threads for example, then pass a function to the callback before_exit:
```Python
def my_call_on_exit():
   # Close all other window or set a variable to signal closing.
   # Or, let other window know that hello_imgui just closed.
   # Beware that other libs might have issues with calls from other threads.
   #   SEGFAULT is the least you can expect in that case.

runner_params = hello_imgui.RunnerParams()
runner_params.callbacks.before_exit = my_call_on_exit
```
2. If you want to close hello_imgui along closing other windows, you would need to signal hello_imgui to do just that:
```Python
runner_params.app_shall_exit = True
```
As soon as you've set that variable, thankfully regardless from whichever thread, hello_imgui will close.

I appreciate that immapp simplifies many things, but due to the lack of documentation, I find pure hello_imgui a bit more adjustable for my purpose.

**Comment by pthom** [comment]
Thanks for the info.

Immapp is very small and its main api is « immapp.run(addons , runnerparams) » where runnerparams are from hello imgui.

Everything’s that is possible with hello imgui should be possible within immapp (you have access to the same params)

could you tell me what you found confusing so that I can try to improve the documentation?

**Comment by Johndeep** [comment]
Well, I mean what I said. Besides [this](https://pthom.github.io/hello_imgui/book/doc_params.html), which is C/C++ only, there seems to be a lack of documentation dedicated for Python.
Of course, if you're already familiar of wrappings of C++ for Python, you merely need to know that CamelCase written functions like `VoidFunction BeforeExit` becomes `before_exit` in Python.

I found out about this via Intellisense and source code digging that those function actually exists. 

It would be helpful to have short and executable examples without too much comments and enough explanation for specific parts of functions, or for what it can be used. But I can understand that it is quite hard to write a good documentation, since there are many documentations out there for many types of applications and libraries, many of them aren't that great either.

May I allow myself a rather different question regarding the performance of one such hello_imgui window:
Besides the `fps_idling.enable_idling` for framerate control, is it somewhere possible to disable vsync?
Usually I do this `glfw.swap_interval(0)` to improve responsiveness of the interface.

**Comment by pthom** [comment]
> May I allow myself a rather different question regarding the performance of one such hello_imgui window:
Besides the fps_idling.enable_idling for framerate control, is it somewhere possible to disable vsync?
Usually I do this glfw.swap_interval(0) to improve responsiveness of the interface.

Not yet, but this is interesting. I'll study that.

**Comment by Johndeep** [comment]
Just to explain my reasoning behind this:

Since I sync hello_imgui with pyvista, it seems that some elements starts to sync with the framerate with pyvista, which is a bit annoying, since it seems to be lagging then. But in truth, because I use Threads to have sharing memories, Python GIL starts to become a very annoying companion in making everything atomic. And thus lagging. At least that is my assumption.

So if you want to sync two windows with different content in general with `Threads`, be careful to either separate the variables from each other or Python GIL will be the party pooper in being very strictly atomic. Or use `Processes` with either `Manager` or `Value` as sharing points. Annoyingly, it becomes difficult to share Classes or custom Objects. I'll investigate other possible methods or workarounds.

**Comment by pthom** [comment]
>It would be helpful to have short and executable examples without too much comments and enough explanation for specific parts of functions, or for what it can be used. But I can understand that it is quite hard to write a good documentation, since there are many documentations out there for many types of applications and libraries, many of them aren't that great either.

There are a lot of examples in the documentation and in the interactive manual. Did you find them? 
﻿Please look at the video below and show you how to access them. 


https://github.com/pthom/imgui_bundle/assets/7694091/be6244d9-9f38-46b9-b80f-29e97de31fc2

**Comment by Johndeep** [comment]
Thank you for pointing out that page again. To be honest, I've made heavy use of that documentation page plus Code finder and how to write it in Python for quite a while already (I've found it by google though). And I really appreciate that documentation/example page! ^^ At least for general implementation and normal use cases.

Then again, I might currently have particular special cases not or barely covered in the documentation though. It is quite recent that I switched over from glfw backend to hello_imgui for simplification reasons and for being more robust, if something like Ubuntu + Wayland does not work again with the GlfwRenderer(window) from imgui_bundle for example. (Unfortunately, even with the latest build 1.5.0, I still get the context error by calling `GlfwRenderer`. In Wayland. X11 works fine.)

In my case, I wanted to push the possibilities how to handle two windows with different context (one of them being hello_imgui) as smooth as possible. What I've found out by looking into the docs and tinkering:
1. In your demos, it seems that you're not consistent with using either `hello_imgui.RunnerParams()` or `immapp.RunnerParams()`. Well, you're using both across the demos and examples. Some times this, then that, or mixed.
2. It seems to me that it might be wiser just to extend hello_imgui instead of having both hello_imgui and immapp, since, if you make use use of the RunnerParams for maximum control, it seems the same to me. While I favor hello_imgui, it might be confusing for new people to see both being used alternatively. One might ask, "so what's the difference besides immapp being able to make a window in a single line?".
3. The example run "demo_python_context_manager" ends into a "Not found" page unfortunately.
4. It seems that setting `fps_idle` has a big impact on the startup time of the app. For example, I set it to 1 second, it will take around 1-2 seconds to start up. (at 0.5 it takes 4-5 seconds) The lower the value, the longer the boot up. One might want to set that parameter _after_ the hello_imgui window is actually shown. But that's minor.. unless you set it to 0.001, which would take 16 minutes to actually show a window...
5. Oh yeah, dunno if it is because being in the web, but the fps demo on the website always tops at, in my case, 60 fps, regardless of fps_idle value.

That's it so far.

**Comment by Johndeep** [comment]
It's good to see the startup problem with `fps_idle` has a solution in the latest release (1.5.2) by delaying the idle fps by some seconds.

**Comment by pthom** [comment]
In the case of multi-threading you might want to update to the latest version which adds another correction, i.e. release the GIL when idling.

See https://github.com/pthom/imgui_bundle/commit/c48e7618c7b439475ce5ecfc4b6da3c09a3749be

You will have to either compile from source, or download a precompiled wheel from here:

https://github.com/pthom/imgui_bundle/actions/workflows/wheels.yml

**Comment by thiago4455** [comment]
> I tried to do threads again and found out that is **does** work, as long as I keep it at only one instance. As soon as I add another window per thread, everything just shuts down. Just like that.

Hi there. Can you share an example of _how_ could you make it work with threads? I need only one GUI, but it needs to be off the main thread.

**Comment by pthom** [comment]
Hi @Johndeep 

Thanks for your example. Beware, the result might be OS dependent: based on my test, this does not work on macOS. On which OS did you run this code?

**Comment by Johndeep** [comment]
Well, my "get to go for everything" OS is always Linux, in this time and era though, it is currently good ol' Ubuntu, because it just works (24.04.2 LTS). I created a venv with Python 3.12 and additionally installed imgui_bundle via pip. That's it.

But I am curious, what exactly does not work (what warnings or errors)? I mean, the code is as simple and stripped as I could get.

**Comment by pthom** [comment]
> But I am curious, what exactly does not work (what warnings or errors)?

Uner macOS, no error or warning is shown in the console, but the GUI will not sow

**Comment by Johndeep** [comment]
I assume you already tried a "dry run" without threading and directly calling the `task_thread` function? Just to make sure that the problem indeed lies in the threading package of Python?

**Comment by pthom** [comment]
Ofc I did

**Comment by Johndeep** [comment]
Okay, I whip up an elaborate example with glfw as the main actor this time:

```Python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import threading

import OpenGL.GL as gl
from imgui_bundle import imgui
from imgui_bundle.glfw_utils import glfw
from imgui_bundle.python_backends.glfw_backend import GlfwRenderer


def impl_glfw_init():
    """Inits for glfw stuff"""

    width, height = 300, 200
    window_name = "minimal ImGui/GLFW3 example"

    if not glfw.init():
        print("Could not initialize OpenGL context")
        sys.exit(1)

    # OS X supports only forward-compatible core profiles from 3.2
    glfw.window_hint(glfw.CONTEXT_VERSION_MAJOR, 3)
    glfw.window_hint(glfw.CONTEXT_VERSION_MINOR, 3)
    glfw.window_hint(glfw.OPENGL_PROFILE, glfw.OPENGL_CORE_PROFILE)

    glfw.window_hint(glfw.OPENGL_FORWARD_COMPAT, gl.GL_TRUE)

    # Create a windowed mode window and its OpenGL context
    window = glfw.create_window(width, height, window_name, None, None)
    glfw.make_context_current(window)

    if not window:
        glfw.terminate()
        print("Could not initialize Window")
        sys.exit(1)

    return window


def task_thread():
    """This will be threaded, please check if this also works in MacOS"""

    glfw.init()
    window = impl_glfw_init()

    imgui.create_context()
    impl = GlfwRenderer(window)

    while not glfw.window_should_close(window):

        glfw.poll_events()
        impl.process_inputs()

        imgui.new_frame()
        imgui.text("Hallo Welt!")

        gl.glClearColor(0.0, 0.0, 0.0, 1)
        gl.glClear(gl.GL_COLOR_BUFFER_BIT)

        imgui.render()
        impl.render(imgui.get_draw_data())
        glfw.swap_buffers(window)

    impl.shutdown()
    glfw.terminate()


if __name__ == "__main__":

    my_thread = threading.Thread(target=task_thread)
    my_thread.start()

    # If you want to test the behavior of another imgui instance, here you go
    # my_other_thread = threading.Thread(target=task_thread)
    # my_other_thread.start()

    # Do other stuff
    print("This outputs while thread is going on")

    my_thread.join()
    # my_other_thread.join()

    print("This outputs after the end of thread")
```

Please check if this works out for any of you. In my case as I already mentioned it [here](https://github.com/pyimgui/pyimgui/issues/318), I need to declare an environment variable "PYOPENGL_PLATFORM": "glx" (with Ubuntu 24.04) to make it work correctly. I guess Windows and MacOS do not need that.

**Comment by pthom** [comment]
This version also blocks: the call to `glfw.create_window(...)` never returns in a thread under macOS (and of course your code works without threading).

I am not surprised : as the [glfw doc](https://www.glfw.org/docs/3.3/group__window.html) mentions, many functions "must only be called from the main thread". 
A possible explanation here: [Cocoa event processing is tied to the main thread ](https://github.com/glfw/glfw/issues/136)

**Comment by Johndeep** [comment]
Well then, just to have another code snippet to test the possible issue regarding the Cocoa event processing on MacOS, here another example, this time based on sdl2:

```Python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
@File    :   minimal_imgui_sdl.py
@Time    :   2025/04/18 12:31:10
"""

import sys
import threading

import OpenGL.GL as gl
import sdl2
from imgui_bundle import imgui
from imgui_bundle.python_backends.sdl_backend import SDL2Renderer


def impl_sdl_init():
    """Inits for sdl stuff"""

    sdl2.SDL_Init(sdl2.SDL_INIT_VIDEO)

    sdl2.SDL_GL_SetAttribute(sdl2.SDL_GL_CONTEXT_MAJOR_VERSION, 3)
    sdl2.SDL_GL_SetAttribute(sdl2.SDL_GL_CONTEXT_MINOR_VERSION, 3)
    sdl2.SDL_GL_SetAttribute(
        sdl2.SDL_GL_CONTEXT_PROFILE_MASK, sdl2.SDL_GL_CONTEXT_PROFILE_CORE
    )

    window = sdl2.SDL_CreateWindow(
        b"Threaded",
        sdl2.SDL_WINDOWPOS_CENTERED,
        sdl2.SDL_WINDOWPOS_CENTERED,
        300,
        200,
        sdl2.SDL_WINDOW_OPENGL | sdl2.SDL_WINDOW_RESIZABLE | sdl2.SDL_WINDOW_SHOWN,
    )
    if not window:
        print("Could not initialize Window")
        sys.exit(1)

    glcontext = sdl2.SDL_GL_CreateContext(window)
    if glcontext is None:
        print("Error: Cannot create OpenGL Context!")
        sys.exit(1)

    sdl2.SDL_GL_MakeCurrent(window, glcontext)

    return window, glcontext


def task_thread():
    """This will be threaded, please check if this also works in MacOS"""

    window, glcontext = impl_sdl_init()

    imgui.create_context()
    impl = SDL2Renderer(window)

    running = True
    while running:

        event = sdl2.SDL_Event()
        while sdl2.SDL_PollEvent(event) != 0:
            if event.type == sdl2.SDL_QUIT:
                running = False
                break
            # Just some quality of life enhancements, namely quitting via keypress
            if event.type == sdl2.SDL_KEYDOWN:
                if event.key.keysym.sym in [sdl2.SDLK_ESCAPE, sdl2.SDLK_q]:
                    running = False
                    break

            impl.process_event(event)

        impl.process_inputs()

        imgui.new_frame()
        imgui.text("Hallo Welt!")

        gl.glClearColor(0.0, 0.0, 0.0, 1)
        gl.glClear(gl.GL_COLOR_BUFFER_BIT)

        imgui.render()
        impl.render(imgui.get_draw_data())

        sdl2.SDL_GL_SwapWindow(window)

    sdl2.SDL_GL_DeleteContext(glcontext)
    sdl2.SDL_DestroyWindow(window)
    sdl2.SDL_Quit()


if __name__ == "__main__":

    # Dry run
    # task_thread()

    my_thread = threading.Thread(target=task_thread)
    my_thread.start()

    # If you want to test the behavior of another imgui instance, here you go
    # my_other_thread = threading.Thread(target=task_thread)
    # my_other_thread.start()

    # Do other stuff
    print("This outputs while thread is going on")

    my_thread.join()
    # my_other_thread.join()

    print("This outputs after the end of thread")
```

This also has the same annoying problem with the need of "PYOPENGL_PLATFORM": "glx" in my case. But then it also should work just fine (at least within Ubuntu/Linux again). Happy testing.

**Comment by thiago4455** [comment]
Thanks for all the snippets! My initial attempts were similar to your example, but I am also using macOS, so I suppose that's why Im struggling.

Your latest snippet also works fine in a dry run, but in threading fails with:
```bash
This outputs while thread is going on
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'API misuse: setting the main menu on a non-main thread. Main menu contents should only be modified from the main thread.'
```

<details>
<summary>Call stack:</summary>

```bash
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001954cae80 __exceptionPreprocess + 176
	1   libobjc.A.dylib                     0x0000000194fb2cd8 objc_exception_throw + 88
	2   Foundation                          0x00000001966d9978 -[NSCalendarDate initWithCoder:] + 0
	3   AppKit                              0x0000000198f9e060 -[NSMenu _setMenuName:] + 468
	4   AppKit                              0x0000000198fb2bb8 -[NSApplication setMainMenu:] + 372
	5   libSDL2-2.0.0.dylib                 0x0000000101fc7f50 Cocoa_RegisterApp + 428
	6   libSDL2-2.0.0.dylib                 0x0000000101fcdaa8 Cocoa_CreateDevice + 28
	7   libSDL2-2.0.0.dylib                 0x0000000101fb58cc SDL_VideoInit_REAL + 496
	8   libSDL2-2.0.0.dylib                 0x0000000101f2c51c SDL_InitSubSystem_REAL + 408
	9   libffi.dylib                        0x00000001a7129050 ffi_call_SYSV + 80
	10  libffi.dylib                        0x00000001a7131b04 ffi_call_int + 1208
	11  _ctypes.cpython-313-darwin.so       0x00000001011b3330 _ctypes_callproc + 772
	12  _ctypes.cpython-313-darwin.so       0x00000001011b0a20 PyCFuncPtr_call + 260
	13  Python                              0x00000001013bdc08 _PyObject_MakeTpCall + 124
	14  Python                              0x00000001014e6664 _PyEval_EvalFrameDefault + 9684
	15  Python                              0x00000001013c1460 method_vectorcall + 396
	16  Python                              0x00000001015dd174 thread_run + 152
	17  Python                              0x000000010156929c pythread_wrapper + 48
	18  libsystem_pthread.dylib             0x00000001953702e4 _pthread_start + 136
	19  libsystem_pthread.dylib             0x000000019536b0fc thread_start + 8
)
libc++abi: terminating due to uncaught exception of type NSException
```
</details>

**Comment by Johndeep** [comment]
Well then, I think the message is unfortunately clear, namely `Main menu contents should only be modified from the main thread.` as pthom already suspected. This is almost as annoying as the GIL in Python (at least there is an option to disable that from 3.13 onward).

Then may I suggest using `multiprocessing` to you instead? Or rather, does MacOS _at least_ allow you to run the main in a Process? Did anyone test that already?

```Python
# import threading
import multiprocessing

# [...]

if __name__ == "__main__":

    # Dry run
    # task_thread()

    # my_thread = threading.Thread(target=task_thread)
    my_thread = multiprocessing.Process(target=task_thread)

    # [...]
```

**Comment by thiago4455** [comment]
> Or rather, does MacOS at least allow you to run the main in a Process?

Yes it does, and runs as expected even with multiple windows. 
My use case relies on shared memory, so It doesn't help that much. But I figured out how to run the rest of my application outside the main thread, so I can have the GUI blocking the main one just fine
