### ISSUE TITLE
demo_hello_world.py fails due to circular import

### ISSUE THREAD

**Issue by maxmbed** [pthom/imgui_bundle#227]
Hi,

I am encountering a problem to run python [demo_hello_world.py](https://github.com/pthom/imgui_bundle/blob/main/bindings/imgui_bundle/demos_python/demos_immapp/demo_hello_world.py). 
it likely fails due to a circular import problem.

```bash
➜  palette (.venv) python demo_hello_world.py
Traceback (most recent call last):
  File "/home/max/Development/Python/palette/imgui_bundle.py", line 1, in <module>
    from imgui_bundle import immapp
  File "/home/max/Development/Python/palette/imgui_bundle.py", line 1, in <module>
    from imgui_bundle import immapp
ImportError: cannot import name 'immapp' from partially initialized module 'imgui_bundle' (most likely due to a circular import)
```

I follow the [installation instruction](https://github.com/pthom/imgui_bundle?tab=readme-ov-file#install-from-pypi) in virtual environment.

Python version is `3.12.3`

Is this an usual problem ?

**Comment by pthom** [comment]
Hellon

No, this is not a usual problem. Did you install from source or did you install using pipy?

I just did an installation from both source or using pipy, and both worked. 
Could you try to install in a fresh environment? 
If it still fails, please give me a full summary of all the commands you run, + the OS.

**Comment by maxmbed** [comment]
Thanks for your feedback. It was installed using pipy.

I run demo again using another fresh environment and it works good.

Actually,  I am stupid. I name the source file `imgui_bundle.py` . After rename it, the issue gone.
