### ISSUE TITLE
Can we add the addition operation for imgui.ImVec2 to the release? The library I downloaded from PyPI does not support this operation.

### ISSUE THREAD

**Issue by iloveyehan** [pthom/imgui_bundle#232]
`

**Comment by pthom** [comment]
Hello 

[v1.5.2](https://pypi.org/project/imgui-bundle/1.5.2/) is out, it adds support for math operators, and much more.

See changelog: https://github.com/pthom/imgui_bundle/releases/tag/v1.5.2


cheers
