### ISSUE TITLE
Displaying images stored in numpy arrays

### ISSUE THREAD

**Issue by mafried** [pthom/imgui_bundle#235]
Hi, 

I would like to display images stored in numpy arrays (I'm using the python bindings of imgui_bundle).
I'm using imgui.image(...) for that but I don't know how to transform the numpy array into a texture. 
I've used PyImGUI in the past together with the moderngl package where texture creation from numpy arrays is simple.
Since PyImGUI seems not to be maintained anymore, I switched to imgui_bundle.

Now, I tried the same thing with imgui_bundle and immapp but could not find anything helpful.

Thank you! 

Best regards

**Comment by pthom** [comment]
Hello,

Just try immvision.image_display or immvision.image

https://github.com/pthom/imgui_bundle/assets/7694091/47209271-0de6-4ba4-bd96-9346e8f5d606

**Comment by mafried** [comment]
Hi, 
Thank you so much for your quick and thorough reply! I'm using the immvision image widget and it's working great.
