### ISSUE TITLE
Compilation error when disabling ImPlot

### ISSUE THREAD

**Issue by adepierre** [pthom/imgui_bundle#242]
Hello, and thank you for this project!

I tried to setup an base example with IMGUI_BUNDLE_DISABLE_IMPLOT set to ON. But then the build fails because immapp has some #include with implot headers (for example [here](https://github.com/pthom/imgui_bundle/blob/7d8fd2159b62389f8c8d2a9eecaa16482a957e29/external/immapp/immapp/immapp_widgets.cpp#L4))

**Comment by pthom** [comment]
Hello, thanks for reporting this. 

This was fixed here: https://github.com/pthom/imgui_bundle/commit/226ecaa9064321d2194020273a311b03013b098a
