### ISSUE TITLE
Pyglet Pure Python Backend doesn't work with python 3.12+ due to distutils removal

### ISSUE THREAD

**Issue by DragonMoffon** [pthom/imgui_bundle#249]
https://github.com/pthom/imgui_bundle/blob/be8339b41ae36e3cd0de372f151ef9590ef44eee/bindings/imgui_bundle/python_backends/pyglet_backend.py#L224-L236

This function still uses the deprecated `distutils` module's `LooseVersion`. It appears the recommended fix is to use `packaging.version.parse`.

https://packaging.pypa.io/en/latest/version.html

**Comment by DragonMoffon** [comment]
So I've looked into how Distutils looseversion works, and it's quite simple. It just converts the version into a list (converting what it can to ints) and then does piecewise comparisons.

I'll make a small PR removing distutils when I can. Do you know any other places distutils might be used? I'll do a full cleanup.

**Comment by pthom** [comment]
Hello, and thank you for your answer!

> I'll make a small PR removing distutils when I can. 

Great news

> Do you know any other places distutils might be used? I'll do a full cleanup.

I think this is the only place it is used.

**Comment by eruvanos** [comment]
@pthom is it possible to release a patch version with this update?
