### ISSUE TITLE
demo_tex_inspect problems

### ISSUE THREAD

**Issue by dcnieho** [pthom/imgui_bundle#26]
1. Running it gives me a window that is vertically so big it doesn't fit on my screen.
2. when running i do get an error:
```ERROR: ImGui_ImplOpenGL3_CreateDeviceObjects: failed to compile fragment shader!
ERROR: 1:23: 'function' : is removed in Forward Compatible context texture2D
ERROR: 1:23: 'texture2D' : no matching overloaded function found (using implicit conversion)
ERROR: 1:23: 'texture2D' : function is not known
ERROR: 1:23: '+' : wrong operand types no operation '+' exists that takes a left-hand operand of type '4X4 matrix of highp float' and a right operand of type 'uniform 4-component vector of highp float' (or there is no acceptable conversion)
ERROR: 1:23: '=' :  cannot convert from '4X4 matrix of highp float' to '4-component vector of highp float'


ERROR: ImGui_ImplOpenGL3_CreateDeviceObjects: failed to link shader program! (with GLSL '#version 130
')
Attached fragment shader is not compiled.```

It does seem to work, so perhaps not an issue otherwise. Keep it and report to library author?

**Comment by pthom** [comment]
This should be fixed by the last two commits here: 
https://github.com/pthom/imgui_tex_inspect/commits/imgui_bundle_fixes

A PR was submitted to the original author [here](https://github.com/andyborrell/imgui_tex_inspect/pull/5)

Please inform me whether it also works on your side: shaders are notoriously GPU and system dependent.

**Comment by dcnieho** [comment]
Yes, works for me too now, without error. The window this demo opens is however still too tall vertically, the window bar is offscreen.
