### ISSUE TITLE
Overloaded operators for ImVec2, 3, etc.

### ISSUE THREAD

**Issue by oxysoft** [pthom/imgui_bundle#267]
Currently this does not work

```python
a = ImVec2(0, 0)
b = ImVec2(1, 1)
c = a + b
```

Overloaded operators for vector operations would be amazing and crucial for building more complex applications!

**Comment by pthom** [comment]
Hello,

Those operators were defined, but not made explicit in the stub file, so that your IDE may warn about this.
They are now declared in the stubs.
