### ISSUE TITLE
imgui_bundle_demo observations

### ISSUE THREAD

**Issue by dcnieho** [pthom/imgui_bundle#28]
I have now run `imgui_bundle_demo` after a successful pip install. observations:
1. on the imgui bundle screen the list of libraries under about/batteries included needs to be updated
2. the text editor with code under immediate mode gui is too small on my hidpi screen. Same for the ones under basic code advices (which should be advice by the way), and the other nodes under that
3. should the log buttons under advanced create items in some log? I don't see any log listing anywhere there. Oh wait, now i get it, those are not buttons to create some fake items, but for filtering the log. running the glfw callback demo creates some entries. Works fine, just didn't understand it.
4. in demo apps, clicking `imgui_example_glfw_opengl3` works, but opens a window that is not DPI scaled, everything is tiny. Not sure if you want to fix that. It also opens a popup with app code that i can't close again, only collapse
5. demo_custom_fonts works nicely and is correctly scaled
6. Docking demo button: demo works nicely, only one small thing is that the progress bar when launching the rocket seems to not be dpi scaled, this is what i get: 
![image](https://user-images.githubusercontent.com/1787673/205482452-5039f73d-d77d-42c7-9c9a-ac9dd257e6e6.png)
  also, not all GUI elements work in some of the color schemes (try light) but that might not be something you can do anythign about.
7. implot tab: all works well, but like the haiku, all the plots are not tall enough. Screenshot: 
![image](https://user-images.githubusercontent.com/1787673/205482548-611fdc23-3187-4227-980c-2150bcb88c77.png)
8. Markdown spacing isn't great (hidpi problem?), see e.g.: 
![image](https://user-images.githubusercontent.com/1787673/205482619-6e060e7c-9c12-4c2f-8050-a31407b97974.png)
  and also the spacing after the full stop between sentences in the implot screenshot above (seems not enough space after full stop)
9. editor demo: link not parsed correctly? 
![image](https://user-images.githubusercontent.com/1787673/205482710-7a65d4e9-8178-4181-9275-fd6a3c6ad49a.png)
also, clicking ´test glfw link´ takes the window almost offscreen (top left), can hardly access the Windows window bar to drag it back. maybe set window pos 100,100 instead of 10,10?
10. additional widgets: all works, but imfiledialog widgets open way too small, guess another hidpi thing. Spinners are possibly a bit small: 
![image](https://user-images.githubusercontent.com/1787673/205482831-70b116ec-f28a-48d1-b1ae-80f1448cbedf.png)
11. something while running the imgui_bundle_demo also put `ImGuiMd::OnOpenLink_Default url "images/world.jpg" should start with http!` on the command line. Perhaps you know what triggered that.

**Comment by pthom** [comment]
> the text editor with code under immediate mode gui is too small on my hidpi screen. Same for the ones under basic code advices (which should be advice by the way), and the other nodes under that

Fixed

> Docking demo button: demo works nicely, only one small thing is that the progress bar when launching the rocket seems to not be dpi scaled, this is what i get:

Fixed

> implot tab: all works well, but like the haiku, all the plots are not tall enough. 

Fixed

> Spinners are possibly a bit small:
Fixed

> editor demo: link not parsed correctly?

Fixed

> Haiku heart demo: the height of the plot window is too small, making it very horizontally stretched. Also, when making the window wider, the plot stretches horizontally with the window, but not vertically even though there is plenty of space, making it even more horizontally stretched out.

Fixed
----

> in demo apps, clicking imgui_example_glfw_opengl3 works, but opens a window that is not DPI scaled, everything is tiny. Not sure if you want to fix that. It also opens a popup with app code that i can't close again, only collapse

This is the port of the official imgui example, which does not handle DPI. I will not change it at this time. Thanks for reporting.

----

### Remaining issues

>  imfiledialog widgets open way too small, guess another hidpi thing. 

Still needs to be correct

> on the imgui bundle screen the list of libraries under about/batteries included needs to be updated

Of course, this will be done for the next release (which is coming soon)

> Sizing of toggle and knobs broken on high DPI

Will need to be repaired in third party code

>

**Comment by dcnieho** [comment]
I just pulled the latest code from dev and compiled. Demo's are looking very nice! Good sizing now too on many items, i confirm your fixes.

One issue that remains besides imfiledialog sizing is that markdown spacing for sentences is still messed up. See here the Advices section:
![image](https://user-images.githubusercontent.com/1787673/207736850-c64497a5-4042-41cc-a678-de583ee4d2ee.png)
Space is missing after dots so the lists look messy and the sublist looks like a typo instead (I read "handleda").

The imgui_node_editor demo is too small on my hi dpi screen

When i clicked my menu in the docking demo of `imgui_bundle_demo` i got:
```
(venv) C:\Users\huml-dkn\Desktop\imgui_bundle>imgui_bundle_demo
Traceback (most recent call last):
  File "C:\Users\huml-dkn\Desktop\imgui_bundle\venv\lib\site-packages\imgui_bundle\demos\demos_immapp\demo_docking.py", line 323, in <module>
    main()
  File "C:\Users\huml-dkn\Desktop\imgui_bundle\venv\lib\site-packages\imgui_bundle\demos\demos_immapp\demo_docking.py", line 319, in main
    immapp.run(runner_params, addons_params)
  File "C:\Users\huml-dkn\Desktop\imgui_bundle\venv\lib\site-packages\imgui_bundle\demos\demos_immapp\demo_docking.py", line 224, in show_menu_gui
    if imgui.menu_item("Test me"):
TypeError: menu_item(): incompatible function arguments. The following argument types are supported:
    1. (label: str, shortcut: str, p_selected: bool, enabled: bool = True) -> Tuple[bool, bool]

Invoked with: 'Test me'
```

Regarding toggles, some have a good size, some are small. Spinner some seem a bit small:
![image](https://user-images.githubusercontent.com/1787673/207738443-0ad83622-73ab-4a74-aaa2-aa9204329c10.png)


The knobs on the other hands are maybe a bit too big?
![image](https://user-images.githubusercontent.com/1787673/207738545-f6214724-90da-4d17-8e0c-5882a3c5af17.png)

the texture inspector demo, both cpp and clicked from imgui_bundle_demo open too large, the top window bar is above my screen and it thus can't interact with it. Sizing for the more advanced demo is not right (text doesn't fit in many places):
![image](https://user-images.githubusercontent.com/1787673/207738830-8a0df0e4-16f6-435e-9f66-3ef70a6b014d.png)
Also, no C++ example code for either texture inspect demo is shown in the GUI (I guess you know)

Also, one of the checkboxes is overlaid by the grey checkbox:
![image](https://user-images.githubusercontent.com/1787673/207739188-ab43284a-be39-4923-87d8-a71bc18dc4d9.png)

**Comment by pthom** [comment]
Hi, thanks for the review.
DPI aware sizing is hard with ImGui, and many third parties do not handle it, which is the case of what you showed.

I worked on an experimental hack inside imgui.h:

https://github.com/pthom/imgui/commit/7ca0524ca13723a5c8bb8388efb0eda538e200e8

I don't think we can use it, it would be a bit controversial, but food for thought.

**Comment by dcnieho** [comment]
I like it, I would suggest posting it as an idea on the imgui github, see what others say. At least it'll hopefully start/continue a much needed conversation.

**Comment by dcnieho** [comment]
Great work on making markdown hidpi aware, it looks so much better now! The one thing left that i noted is that the line for underlining and strikethrough is still 1 pixel thick and thus hardly visible. Its thickness should be dpi-scaled.

Now that immvision demo is included by default, some hidpi comments:
1. There is a bit much vertical spacing in the text introducing immvision:
![image](https://user-images.githubusercontent.com/1787673/208211097-7ec8773d-15fb-4927-b55b-3a259e03c167.png)
2. linked images zoom: the icons on the buttons are not scaled. Rightmost button mostly overlaps the one before. Pixel values in the bottom are not legible
![image](https://user-images.githubusercontent.com/1787673/208210788-ec412802-2bf4-4f04-ab55-5ef7f2cfa6ba.png)
3. Image inspector: the image previews on the left are only a few pixels large and thus can't see them. The text giving information about pixels in the viewer in the middle is not dpi scaled and thus too small to read. the text on the buttons on the right does not fit. I made an extra narrow screenshot so i can show everything at once, but the issues are the same with a normal-width window.
![image](https://user-images.githubusercontent.com/1787673/208211160-2085b4f3-8ce1-4170-8fae-61e08b8ff115.png)
4. image processing example: The color selector in the "original" box doesn't work. When you click a color it jumps right back to the previous color. see various issues with text next to the deriv image in the screenshot. The selected colormap has a thick edge that makes it move rightward in the list and extra spaced from the other items
![image](https://user-images.githubusercontent.com/1787673/208212092-9e09db19-ed5a-4063-8af8-b03f99364f0e.png)
