### ISSUE TITLE
Bug in ImGuizmo in 1.6.0 

### ISSUE THREAD

**Issue by jc211** [pthom/imgui_bundle#288]
The manipulate function in imguizmo no longer returns a proper matrix. It returns A matrix, but its not a rigid transform anymore. Im not sure if its a bug or if it now means a different thing. I had to revert back to 1.5.2 to get it working again.

**Comment by pthom** [comment]
This is a known issue in 1.6.0, soon to be fixed in 1.6.1: see https://github.com/pthom/imgui_bundle/blob/main/CHANGELOG.md#v161-work-in-progress

**Comment by pthom** [comment]
In the meantime, you can download a recent wheel here: https://github.com/pthom/imgui_bundle/actions/workflows/wheels.yml

**Comment by jc211** [comment]
Awesome thank you :) and thank you for the hard work maintaining this repo

**Comment by jc211** [comment]
Hey just wondering: why was imguizmo changed from np.array to Matrix16?

**Comment by pthom** [comment]
> Hey just wondering: why was imguizmo changed from np.array to Matrix16?

Hi, 

This happened during the transition between pybind to nanobind for the bindings. Maintaining the old code which did painful transcript to np.arrays got harder with nanobind. And actually, I do feel that the newer API is easier to use.
