### ISSUE TITLE
ImGuiStyle::Colors (and other arrays) not accessible from python bindings

### ISSUE THREAD

**Issue by dcnieho** [pthom/imgui_bundle#29]
In the app i'm porting, I manually modify the default style by modifying the values in the ´ImGuiStyle::Colors` (`imgui.get_style().colors` in pyimgui). This doesn't seem to exist in your port. How do i set specific colors/modify my current style?

Same for KeysDown (should be imgui.get_io().keys_down) and a bunch of other arrays in the ImGuiIO struct. As these have known size, i guess there is a bigger chance they may be wrappable?

**Comment by pthom** [comment]
### Numeric and bool arrays: 

Some of the arrays are already available (those which use numeric or bool items) 

For example, ImGuiIO::bool MouseDown[5] is already available as imgui.get_io().mouse_down
(it is published as read only, i.e. changes made in python are not propagated to C++)


### arrays with user defined types, such as `ImVec4      Colors[ImGuiCol_COUNT]`

This requires a modifications on the generator side.


### Obsolete arrays:

> Same for KeysDown

KeysDown is part of an obsolete API, which the generator willfully ignores (and will continue to ignore).

See relevant imgui.h part:
````cpp
    // Legacy: before 1.87, we required backend to fill io.KeyMap[] (imgui->native map) during initialization and io.KeysDown[] (native indices) every frame.
    // This is still temporarily supported as a legacy feature. However the new preferred scheme is for backend to call io.AddKeyEvent().
    //   Old (<1.87):  ImGui::IsKeyPressed(ImGui::GetIO().KeyMap[ImGuiKey_Space]) --> New (1.87+) ImGui::IsKeyPressed(ImGuiKey_Space)

#ifndef IMGUI_DISABLE_OBSOLETE_KEYIO
    int         KeyMap[ImGuiKey_COUNT];             // [LEGACY] Input: map of indices into the KeysDown[512] entries array which represent your "native" keyboard state. The first 512 are now unused and should be kept zero. Legacy backend will write into KeyMap[] using ImGuiKey_ indices which are always >512.
    bool        KeysDown[ImGuiKey_COUNT];           // [LEGACY] Input: Keyboard keys that are pressed (ideally left in the "native" order your engine has access to keyboard keys, so you can use your own defines/enums for keys). This used to be [512] sized. It is now ImGuiKey_COUNT to allow legacy io.KeysDown[GetKeyIndex(...)] to work without an overflow.
    float       NavInputs[ImGuiNavInput_COUNT];     // [LEGACY] Since 1.88, NavInputs[] was removed. Backends from 1.60 to 1.86 won't build. Feed gamepad inputs via io.AddKeyEvent() and ImGuiKey_GamepadXXX enums.
#endif

````

**Comment by pthom** [comment]
I quickly scanned the arrays in imgui.get_io() and imgui.get_style():

* the bool/int/float arrays were already published (and bool arrays are published as read only)
* the obsolete arrays are still not published (KeysDown)

The only missing I saw was ImGuiStyle::Colors. I decided not to patch the generator for the moment, so I added an alternative solutioon by patching imgui:
 https://github.com/pthom/imgui/commit/a08931272922462f8bd4afb52011f8b5bc6a6ebe


I think it should be enough. Please tell me whether is is or not, so that I can close this issue

**Comment by pthom** [comment]
I'm still wonder if the api could be improved, i.e by having get_colors return a modifiable color and thus avoid set_color

**Comment by pthom** [comment]
PS: I noted the generator idea here, to be handled later: https://github.com/pthom/imgui_bundle/discussions/38

**Comment by dcnieho** [comment]
Thanks! Makes sense not to wrap the obsolete arrays. But would it be
possible to expose the actual array instead of getter and setter functions?
That would be the closest to the original API (as well as pyimgui's) and is
therefore easiest to discover/port from C++.

**Comment by pthom** [comment]
>  But would it be
possible to expose the actual array instead of getter and setter functions?
That would be the closest to the original API (as well as pyimgui's) and is
therefore easiest to discover/port from C++.

No. 

````cpp
struct ImGuiStyle
{
   ....
    ImVec4      Colors[ImGuiCol_COUNT];
};
````


C arrays like `int v[10]` are liars: their type is `int *`,  not `int []`. 
The only thing the compiler does to help is to reserve 10 slots and build time, and then it happily drop the size information into oblivion.

As far as pybind11 is concerned, Colors is a ImVec4* with no information whatsoever about its size. 

Porting it to a python would require 

1/ either, patching ImGui like this:

````cpp
struct ImGuiStyle
{
   ....
    ImVector<ImGuiCol> Colors;
};
````
But then  the color info would be on the heap and performance would drop.

2/ Or write dirty hacks which I do not have time to explore  (I'm currently fighting hard with the CI wheels generation)

**Comment by pthom** [comment]
... And at this time I think Github is throttling my wheels build down, since they randomly fail after one hour (either they download corrupted files, or they seg-fault for no good reason)

**Comment by dcnieho** [comment]
> ... And at this time I think Github is throttling my wheels build down, since they randomly fail after one hour (either they download corrupted files, or they seg-fault for no good reason)

Ugh, that sounds very frustrating, I hope you win that fight! I am not very familiar with github's infrastructure, but i think i remember reading about cached artefact or build environments or something like that. I assume time-consuming steps are things like getting OpenCV built. If you could cache the result of that, next time you don't spend time on that and may stay well within the hour?

**Comment by dcnieho** [comment]
But the generator already handles many other fixed-size arrays well, such as (random example) `imgui.get_io().mouse_clicked_count`. More generally, if we look at a section of ImGuiIO and see how its wrapped:
```
struct ImGuiIO
{
   ....
    ImGuiKeyData KeysData[ImGuiKey_KeysData_SIZE];  // Key state for all known keys. Use IsKeyXXX() functions to access this.
    bool        WantCaptureMouseUnlessPopupClose;   // Alternative to WantCaptureMouse: (WantCaptureMouse == true && WantCaptureMouseUnlessPopupClose == false) when a click over void is expected to close a popup.
    ImVec2      MousePosPrev;                       // Previous mouse position (note that MouseDelta is not necessary == MousePos-MousePosPrev, in case either position is invalid)
    ImVec2      MouseClickedPos[5];                 // Position at time of clicking
    double      MouseClickedTime[5];                // Time of last click (used to figure out double-click)
    bool        MouseClicked[5];                    // Mouse button went from !Down to Down (same as MouseClickedCount[x] != 0)
    bool        MouseDoubleClicked[5];              // Has mouse button been double-clicked? (same as MouseClickedCount[x] == 2)
    ImU16       MouseClickedCount[5];               // == 0 (not clicked), == 1 (same as MouseClicked[]), == 2 (double-clicked), == 3 (triple-clicked) etc. when going from !Down to Down
    ImU16       MouseClickedLastCount[5];           // Count successive number of clicks. Stays valid after mouse release. Reset after another click is done.
    bool        MouseReleased[5];                   // Mouse button went from Down to !Down
    bool        MouseDownOwned[5];                  // Track if button was clicked inside a dear imgui window or over void blocked by a popup. We don't request mouse capture from the application if click started outside ImGui bounds.
    bool        MouseDownOwnedUnlessPopupClose[5];  // Track if button was clicked inside a dear imgui window.
    float       MouseDownDuration[5];               // Duration the mouse button has been down (0.0f == just clicked)
    float       MouseDownDurationPrev[5];           // Previous time the mouse button has been down
    ImVec2      MouseDragMaxDistanceAbs[5];         // Maximum distance, absolute, on each axis, of how much mouse has traveled from the clicking point
    float       MouseDragMaxDistanceSqr[5];         // Squared maximum distance of how much mouse has traveled from the clicking point (used for moving thresholds)
    float       NavInputsDownDuration[ImGuiNavInput_COUNT];
    float       NavInputsDownDurationPrev[ImGuiNavInput_COUNT];
    float       PenPressure;                        // Touch/Pen pressure (0.0f to 1.0f, should be >0.0f only when MouseDown[0] == true). Helper storage currently unused by Dear ImGui.
    .....
    ImVector<ImWchar> InputQueueCharacters;
};
```
we see that all fixed size array that:
1. have an integer to denote their size, and
2. are declared as a simple/basic type such as int or float

are wrapped and work. So `float MouseDownDuration[5];` yes, `ImVec2 MouseDragMaxDistanceAbs[5];` and `float       NavInputsDownDuration[ImGuiNavInput_COUNT];` no. The ImVec2 case would work fine (at least on the python side, no complaints about `np.array([imgui.ImVec2(1,2),imgui.ImVec2(3,4)])`, and i guess the generator has to be taught to recognize preprocessor macros. `ImVec4      Colors[ImGuiCol_COUNT];` is a combination of the two ignored above, but should be equally possible. I would say that, in the long run, spending effort on getting these two things fixed maybe a better place to put your energy (or tell me if i can help!) than manual patches such as you did for getting and setting colors now. There would be a bunch more of those to needed to, for instance, wrap a whole bunch of items in `ImGuiIO`. Of course i do not oversee the complexity, and also am not saying this should be done now. But I hope you would consider it at some point.
