### ISSUE TITLE
draw_list.add_image_rounded signature issue?

### ISSUE THREAD

**Issue by dcnieho** [pthom/imgui_bundle#32]
This might be user error. I have an image i want to draw. It is uploaded through direct interaction with OpenGL and i have a texture id. I then call `draw_list.add_image_rounded(texture_id, pos, pos2, *args, flags=flags, **kwargs)` and get the following error
```
TypeError: add_image_rounded(): incompatible function arguments. The following argument types are supported:
    1. (self: imgui_bundle._imgui_bundle.imgui.ImDrawList, user_texture_id: capsule, p_min: imgui_bundle._imgui_bundle.imgui.ImVec2, p_max: imgui_bundle._imgui_bundle.imgui.ImVec2, uv_min: imgui_bundle._imgui_bundle.imgui.ImVec2, uv_max: imgui_bundle._imgui_bundle.imgui.ImVec2, col: int, rounding: float, flags: int = 0) -> None

Invoked with: <imgui_bundle._imgui_bundle.imgui.ImDrawList object at 0x000001973685C630>, 2, <imgui_bundle._imgui_bundle.imgui.ImVec2 object at 0x000001973685C0F0>, <imgui_bundle._imgui_bundle.imgui.ImVec2 object at 0x000001973685C1B0>; kwargs: flags=<ImDrawFlags_.round_corners_all: 240>, rounding=6.0
```
Removing `*args` from the call (its an empty tuple) and explicitly naming the other two arguments as `p_min` and `p_max` doesn't change this, same incompatible arguments error.

`type(self.texture_id)` returns `<class 'numpy.uintc'>`, as is (apparently) returned by `gl.glGenTextures(1)` (`import OpenGL.GL as gl`)
I note that 'add_image_rounded()' expects a capsule, but i do not know what that is or how to provide it. I would expect providing a normal uint, like with other opengl programming, should work.

**Comment by pthom** [comment]
Fixed in cbdc31c3

Proof: this program

````python
import imgui_bundle
from imgui_bundle import imgui, hello_imgui, ImVec2


def make_gui_closure():
    texture_id = None

    def gui():
        nonlocal texture_id
        if texture_id is None:
            texture_id = hello_imgui.im_texture_id_from_asset("images/world.jpg")

        imgui.get_foreground_draw_list().add_image_rounded(
            texture_id,
            p_min = ImVec2(50, 50),
            p_max= ImVec2(300, 300),
            uv_min = ImVec2(0, 0),
            uv_max = ImVec2(1, 1),
            col = 0xffffffff,
            rounding = 50.0)

    return gui


def main():
    gui = make_gui_closure()
    imgui_bundle.run(gui, window_size=(1000, 800))


if __name__ == "__main__":
    main()
````

lead to:

<img width="310" alt="image" src="https://user-images.githubusercontent.com/7694091/206009886-74c3a585-dce6-428a-9c60-47e8fad0c326.png">

**Comment by dcnieho** [comment]
Thanks! works!

Took me a while to figure out another thing that was up though: the pyimgui
version has more default arguments than yours (you match imgui, so its ok).
I did not provide those. The error message was not helpful for that until i
look at it knowing what i know now. Its not about incompatible arguments,
but missing arguments, correct?
```
TypeError: add_image_rounded(): incompatible function arguments. The
following argument types are supported:
    1. (self: imgui_bundle._imgui_bundle.imgui.ImDrawList, user_texture_id:
int, p_min: imgui_bundle._imgui_bundle.imgui.ImVec2, p_max:
imgui_bundle._imgui_bundle.imgui.ImVec2, uv_min:
imgui_bundle._imgui_bundle.imgui.ImVec2, uv_max:
imgui_bundle._imgui_bundle.imgui.ImVec2, col: int, rounding: float, flags:
int = 0) -> None

Invoked with: <imgui_bundle._imgui_bundle.imgui.ImDrawList object at
0x000001E8119B85B0>, 3, (1015.000000, 169.000000), (1590.000000,
744.000000); kwargs: flags=<ImDrawFlags_.round_corners_all: 240>,
rounding=6.0
```

**Comment by pthom** [comment]
> Its not about incompatible arguments, but missing arguments, correct?

````python
TypeError: add_image_rounded(): incompatible function arguments. The
following argument types are supported:
    1. (self: imgui_bundle._imgui_bundle.imgui.ImDrawList, user_texture_id:
int, p_min: imgui_bundle._imgui_bundle.imgui.ImVec2, p_max:
imgui_bundle._imgui_bundle.imgui.ImVec2, uv_min:
imgui_bundle._imgui_bundle.imgui.ImVec2, uv_max:
imgui_bundle._imgui_bundle.imgui.ImVec2, col: int, rounding: float, flags:
int = 0) -> None

Invoked with: <imgui_bundle._imgui_bundle.imgui.ImDrawList object at
0x000001E8119B85B0>, 3, (1015.000000, 169.000000), (1590.000000,
744.000000); kwargs: flags=<ImDrawFlags_.round_corners_all: 240>,
rounding=6.0
````


replace 
````
(1015.000000, 169.000000), (1590.000000,744.000000)
````
by 
````
ImVec2(1015.000000, 169.000000), ImVec2(1590.000000,744.000000)
````

**Comment by dcnieho** [comment]
They are ImVec2s, now that you have a __repr__ (thanks for that!) i guess
they just get printed like that, like a tuple. The problem is that required
arguments uv_min and uv_max are missing, yet the error message doesn't say
that, but talks about incompatible arguments instead. I'm not sure where
these error messages come from (perhaps pybind), but seems like a problem.
Took me very long to figure this one out as i was on the wrong track.

**Comment by pthom** [comment]
The error says "incompatible function arguments. The following argument types are supported", which means that the signature as a whole was not matched. It does not address parameters one by one
