### ISSUE TITLE
ImGuiTableSortSpecs isn't wrapped correctly

### ISSUE THREAD

**Issue by dcnieho** [pthom/imgui_bundle#33]
I think `ImGuiTableSortSpecs` isn't wrapped correctly. `specs` should be a list of `TableColumnSortSpecs`, not a single one. My pyimgui code has `for sort_spec in sort_specs_in.specs`, where `sort_specs_in` is a `ImGuiTableSortSpecs` gotten from `imgui.table_get_sort_specs()`.

**Comment by pthom** [comment]
Argh... 

````cpp
struct ImGuiTableSortSpecs
{
    const ImGuiTableColumnSortSpecs* Specs;     // Pointer to sort spec array.
    int                         SpecsCount;     // Sort spec count. Most often 1. May be > 1 when ImGuiTableFlags_SortMulti is enabled. May be == 0 when ImGuiTableFlags_SortTristate is enabled.
    bool                        SpecsDirty;     // Set to true when specs have changed since last time! Use this to sort again, then clear the flag.

    ImGuiTableSortSpecs()       { memset(this, 0, sizeof(*this)); }
};
````

Once again a dirty antic pointer table, with the infamous Bonnie and Clyde: (`const ImGuiTableColumnSortSpecs* Specs`, `SpecsCount`)

**Comment by pthom** [comment]
Fixed in c04a33d6

**Comment by dcnieho** [comment]
Yeah, there may be more than one if user subsorts on a second column.

Can you reopen this? There is another issue: the `SortDirection` field of sortspecs doesn't appear in the wrapper.

**Comment by pthom** [comment]
> the SortDirection field of sortspecs doesn't appear in the wrapper.
See #42
