### ISSUE TITLE
imgui.save_ini_settings_to_memory() default argument problem

### ISSUE THREAD

**Issue by dcnieho** [pthom/imgui_bundle#34]
`ini = imgui.save_ini_settings_to_memory()` fails even though the one input argument is optional:
```
TypeError: save_ini_settings_to_memory(): incompatible function arguments. The following argument types are supported:
    1. (out_ini_size: int = None) -> str

Invoked with:
```
calling it with e.g. 1000 as argument works fine.

**Comment by pthom** [comment]
The culprit is the antiquated 1970's style signature where the output is split between and output parameter and the function return and no safe guard is provided.

````cpp
IMGUI_API const char*   SaveIniSettingsToMemory(size_t* out_ini_size = NULL);
````

... I'll study this later. 

In the meantime, if you do need to use this, please pass 0 as a paramter, as ImGui will happily write to whichever address you may pass as a parameter.

**Comment by dcnieho** [comment]
It works without input argument now. But is the commit correct?
`__init__.pyi` has `def save_ini_settings_to_memory() -> str`, whereas the
pybind wrapper has:
```
m.def("save_ini_settings_to_memory",    // imgui.h:962
        ImGui::SaveIniSettingsToMemory,
        py::arg("out_ini_size") = py::none(),
        "return a zero-terminated string with the .ini data which you can
save by your own mean. call when io.WantSaveIniSettings is set, then save
data by your own mean and clear io.WantSaveIniSettings.",
        pybind11::return_value_policy::reference);
```
Or I guess it might make sense since the argument is just to output the
string size, which we don't need on the python side?

**Comment by pthom** [comment]
I must have committed the C++ file in a later step, it now says:

````cpp
    m.def("save_ini_settings_to_memory",
        []() -> const char *
        {
            auto SaveIniSettingsToMemory_adapt_exclude_params = []() -> const char *
            {
                auto r = ImGui::SaveIniSettingsToMemory(NULL);
                return r;
            };

            return SaveIniSettingsToMemory_adapt_exclude_params();
        },

````
