### ISSUE TITLE
two versions of imgui.selectable

### ISSUE THREAD

**Issue by dcnieho** [pthom/imgui_bundle#36]
Ok, last comment for now. Nice work man on the wrapper, i got my first windows to show even though not everything works yet. Anyway, what i run in now is that there are two versions of `imgui.selectable` (and i guess there are more like this one) where one takes a bool and returns a bool, and the other takes a pointer to bool and returns a tuple of two bools. Here i made it error so you can see the signatures:
```
TypeError: selectable(): incompatible function arguments. The following argument types are supported:
    1. (label: str, selected: bool = False, flags: int = 0, size: imgui_bundle._imgui_bundle.imgui.ImVec2 = <imgui_bundle._imgui_bundle.imgui.ImVec2 object at 0x00000285EAB525F0>) -> bool
    2. (label: str, p_selected: bool, flags: int = 0, size: imgui_bundle._imgui_bundle.imgui.ImVec2 = <imgui_bundle._imgui_bundle.imgui.ImVec2 object at 0x00000285EA6D2770>) -> Tuple[bool, bool]
```
I want to use the latter, but get the former. Even though both are defined in the generated pybind code. I guess that is because their python function syntax is identical? Both just take a bool. Perhaps this is user error. How do i call the latter one with signature returning `-> Tuple[bool, bool]`?

We had a closely related discussion about this before, IIRC. The two functions are redundant for the python binding, so we have to choose one style. for pyimgui compatibility (and because i know of no other good reason) and additional flexibility (this form is more informative) i vote to only expose version 2. I'm not sure if this case can be automatically detected (that two different c++ function lead to a python function with the same arguments) and the choice automated.

**Comment by pthom** [comment]
This was fixed and required a patch to imgui itself in my fork: 

https://github.com/pthom/imgui/commit/0117bcf0acc751da0ab7220b9f08b020a8476cd6

**Comment by dcnieho** [comment]
Could you disable the other overload so that the behavior is consistent
with that of other toggleables, such as checkbox, in that it returns a
tuple(bool,bool)?

**Comment by dcnieho** [comment]
Thanks for having a look! Note that choosing the other overload makes you
not only internally consistent but also compatible with pyimgui :)

**Comment by dcnieho** [comment]
I just looked through, and i think `ImGui::MenuItem` is the only other one
that suffers from the same problem (two identical signatures on the python
side). Here too it would be good to choose the bool* p_selected version
that leads to returning std::tuple<bool, bool> i think.

**Comment by pthom** [comment]
Thanks for looking at that.

 See b3386fca and 46a3d336

Please tell me if we can close.

**Comment by dcnieho** [comment]
super, thanks!
