### ISSUE TITLE
default value fail for functions taking ImColor

### ISSUE THREAD

**Issue by dcnieho** [pthom/imgui_bundle#53]
I found something that turns out to be a big problem: Functions taking an `ImColor` argument but specifying a ImU32 default value.
An example is this from imspinner:
```
def spinner_ang_triple(
    label: str,
    radius1: float,
    radius2: float,
    radius3: float,
    thickness: float,
    c1: ImColor = 0xffffffff,
    c2: ImColor = 0xffffff80,
    c3: ImColor = 0xffffffff,
    speed: float = 2.8,
    angle: float = IM_PI
    ) -> None:
    pass
```
`0xffffffff` is not an `ImColor`, and thus you get an incompatible function arguments error when not specifying that input argument yourself (or when specifying it using, for example, `imgui.color_convert_float4_to_u32()` as i did). On the C++ side this is not a problem as there is an `ImColor` constructor taking `ImU32` and this is also wrapped by imgui_bundle. However, Python/PyBind would not do this conversion for you automatically and instead you get that incompatible function arguments error.

So, I thought, ah, `ImColor` also needs a bunch of special helper functions like `ImVec2` and `ImVec4`. It does, I didn't have `ImColor` on my radar when i made the other ones. Among those would be a line `py::implicitly_convertible<ImU32, ImColor>();` telling pybind that there is a conversion here, solving the issues we're seeing. However, when i add that, I get an error when importing the module: `ImportError: implicitly_convertible: Unable to find type unsigned int`. Googling that, i find [this](https://github.com/pybind/pybind11/issues/259), and more importantly [this associated PR](https://github.com/pybind/pybind11/pull/264). So, PyBind doesn't support implicit conversion for native types, only for user-defined types. As you see, that PR was not accepted in the end. That means there is a problem here that can only be solved by fixing the signatures of all functions that expect an `ImColor` and specify a default color as an int. I.e., this in the cpp does work:
```
m.def("spinner_ang_triple",
        ImSpinner::SpinnerAngTriple, py::arg("label"), py::arg("radius1"), py::arg("radius2"), py::arg("radius3"), py::arg("thickness"), py::arg("c1") = ImColor(0xffffffff), py::arg("c2") = ImColor(0xffffff80), py::arg("c3") = ImColor(0xffffffff), py::arg("speed") = 2.8f, py::arg("angle") = IM_PI);
```
Note that i added `ImColor()` around the default arguments. The corresponding stub would be:
```
def spinner_ang_triple(
    label: str,
    radius1: float,
    radius2: float,
    radius3: float,
    thickness: float,
    c1: ImColor = ImColor(0xffffffff),
    c2: ImColor = ImColor(0xffffff80),
    c3: ImColor = ImColor(0xffffffff),
    speed: float = 2.8,
    angle: float = IM_PI
    ) -> None:
    pass
```

This is a hairy one to fix... Best would almost be to re-examine adding support for this to pybind. Even if the default arguments are fixed with something like the above (hopefully some kind of opt in mechanism of the generator) that still leaves the problem that users unexpectedly cannot use `ImU32`'s for colors, something you might do when porting from C++ or from `pyimgui` where this did work.

**Comment by pthom** [comment]
Well, I had to manually fix imspinner.h

**Comment by dcnieho** [comment]
Sucks it had to be this way, but it was the only way. Perhaps one of us can send a pull request upstream (though then i would prefer to change color defs in imspinner to the four uints version, I'll have a look). If we get lucky with the maintainer, thats one less problem.

I grepped through imguibundle and all its submodules, i believe this is the only place where we have this problem. So should be all good now.
