### ISSUE TITLE
Could you also bind ImGui's OpenGL2 backend?

### ISSUE THREAD

**Issue by nnop** [pthom/imgui_bundle#78]
Hi, Pascal,

I just met this awesome repo and trying to use it in my projects.
There were some shaders only support OpenGL 2.1/GLSL 120.
So I have to use GL2 in my project.
I saw `imgui_bundle` only binded GL3 backend as below.

https://github.com/pthom/imgui_bundle/blob/92b4db4513dc11e2e56bb44842d0193d48debcc9/external/imgui/bindings/pybind_imgui_backends.cpp#L17-L40

Could you also add the Dear ImGui's [OpenGL2 backend](https://github.com/ocornut/imgui/blob/master/backends/imgui_impl_opengl2.h#L23-L32) support?
```c++
IMGUI_IMPL_API bool     ImGui_ImplOpenGL2_Init();
IMGUI_IMPL_API void     ImGui_ImplOpenGL2_Shutdown();
IMGUI_IMPL_API void     ImGui_ImplOpenGL2_NewFrame();
IMGUI_IMPL_API void     ImGui_ImplOpenGL2_RenderDrawData(ImDrawData* draw_data);


// Called by Init/NewFrame/Shutdown
IMGUI_IMPL_API bool     ImGui_ImplOpenGL2_CreateFontsTexture();
IMGUI_IMPL_API void     ImGui_ImplOpenGL2_DestroyFontsTexture();
IMGUI_IMPL_API bool     ImGui_ImplOpenGL2_CreateDeviceObjects();
IMGUI_IMPL_API void     ImGui_ImplOpenGL2_DestroyDeviceObjects();
```

**Comment by pthom** [comment]
Hello, thanks for the kind words!

This is not in my current target list, sorry. 

However, I can show you how you could test it on your side. If you show me that it works, I might consider it a bit later.

1. Modify external/imgui/bindings/pybind_imgui_backends.cpp:

```cpp
// [...]
#include "imgui/backends/imgui_impl_opengl2.h"

void py_init_module_imgui_backends(py::module& m)
{
// [...]

    m.def("opengl2_init",
          ImGui_ImplOpenGL2_Init);

    m.def("opengl2_shutdown",
          ImGui_ImplOpenGL2_Shutdown);

    // etc
}
```

2. Modify cmake/add_imgui.cmake:

```cmake
# This will create an imgui target with the correct install, include and link options
function(add_imgui imgui_dir)
    if(NOT TARGET imgui)
        file(GLOB imgui_sources ${imgui_dir}/*.h ${imgui_dir}/*.cpp ${imgui_dir}/misc/cpp/*.cpp ${imgui_dir}/misc/cpp/*.h)
        add_library(imgui STATIC ${imgui_sources})

        # Add this line: this is a hack, since this should be done inside HelloImGui
        target_sources(imgui PRIVATE ${imgui_dir}/backends/imgui_impl_opengl2.cpp ${imgui_dir}/backends/imgui_impl_opengl2.h)

```

3. Modify bindings/imgui_bundle/imgui/backends.pyi

```python

+ def opengl2_init() -> bool:
    pass

# etc
```

This should be enough.


Then , write a modified version of the ImGui standalone example: 
bindings/imgui_bundle/demos_python/demos_immapp/imgui_example_glfw_opengl3.py

And test that it works.

**Comment by pthom** [comment]
Update: since this was actually much easier to do than I thought, I did it and just pushed it.

See https://github.com/pthom/imgui_bundle/commit/eb47c3efb84ddf2a7d0c979b426dab4748e8a336

To test it, you can either pip install from source, or check if the prebuild wheels are available for you [here](https://github.com/pthom/imgui_bundle/actions/runs/4090772931) (download and unzip the artifacts)

I plan to release an update to pip (v0.8.3) quite soon.

**Comment by nnop** [comment]
Thanks for the quick update. It works!
