### ISSUE TITLE
Usability issue around MenuItem binding

### ISSUE THREAD

**Issue by pthom** [pthom/imgui_bundle#79]
@dcnieho : this is a question for you

When we last discussed about Selectable and MenuItem, we decided to disable some overload because they had the same signature on the python side.

See https://github.com/pthom/imgui_bundle/issues/36

For MenuItem, we only selected the second overload of those two:

```cpp
#ifdef IMGUI_BUNDLE_PYTHON_UNSUPPORTED_API
    IMGUI_API bool          MenuItem(const char* label, const char* shortcut = NULL, bool selected = false, bool enabled = true);  // return true when activated.
#endif
    IMGUI_API bool          MenuItem(const char* label, const char* shortcut, bool* p_selected, bool enabled = true);              // return true when activated + toggle (*p_selected) if p_selected != NULL
```

However, my opinion is that the second overload is not that friendly in Python. For example, in C++ I can write 

```cpp
if (ImGui::MenuItem("A Custom app menu item"))
      HelloImGui::Log(HelloImGui::LogLevel::Info, "Clicked on A Custom app menu item");
```

However in python, I must write:

```python
  clicked, _ = imgui.menu_item("A Custom app menu item", "", False)
  if clicked:
      hello_imgui.log(hello_imgui.LogLevel.info, "Clicked on A Custom app menu item")
```

The second overload has the advantage (and default) of returning a tuple with the selected bool value. However it is not that difficult to switch from the user side. 

What do you think?

**Comment by dcnieho** [comment]
I think thats just the way it is, we chose this for consistency with pyimgui to keep transitioning simple (i certainly as happy with that). And its also consistent with many other functions in imgui, which take a bool pointer. So probably best to keep it this was, even if it is a bit more verbose and forcing adding variables to local scope?
It is a little more annoying that the default arguments are missing... But still not worth breaking consistency i think.
