### ISSUE TITLE
imgui.internal.dock_builder_split_node not wrapped correctly?

### ISSUE THREAD

**Issue by dcnieho** [pthom/imgui_bundle#93]
It appears `ImGui::DockBuilderSplitNode()` is not wrapped correctly. Its last two parameters are output pointers, yet the python wrapper has them as normal IDs. I think the Python signature should instead be:
```python
# IMGUI_API ImGuiID       DockBuilderSplitNode(ImGuiID node_id, ImGuiDir split_dir, float size_ratio_for_node_at_dir, ImGuiID* out_id_at_dir, ImGuiID* out_id_at_opposite_dir);     /* original C++ signature */
def dock_builder_split_node(
    node_id: ID,
    split_dir: Dir,
    size_ratio_for_node_at_dir: float,
) -> Tuple[ID,ID,ID]:
    """Create 2 child nodes in this parent node."""
    pass
```

**Comment by pthom** [comment]
Hi, this should be fixed by  2874e52 with a manual binding. Beware the name for the bound function is `dock_builder_split_node_py`.

CI is in progress

**Comment by dcnieho** [comment]
Thanks! Looks good! I'll happily use it.

But can't you use the _adapt_modifiable_immutable_to_return machinery for
this one, or is that not possible because of the type (which is really just
an int, but guess you don't know that at that stage in the generator). If
that is the issue, perhaps if possible in the generator, you can add the
option to whitelist additional types for that adaptation?

**Comment by pthom** [comment]
Hi,

Thanks for the advice. This requires a change in the generator. I'll give it a go in the new few days. However the generated API for this particular function may end up unfriendly: it will ask the user to give input values for "output only" parameters.

**Comment by dcnieho** [comment]
hmm, true. Something like the splitter_behavior one was an in-out pointer parameter. Ok, that wouldn't make sense here then. You can't automatically detect if its an in-out or only an out parameter. So that requires config, and probably makes it too complicated then...? I.e. add a new `_adapt_pointer_output_to_return` or so, and a config to say that a specific function (match to pattern) should use that instead of `_adapt_modifiable_immutable_to_return`...
